AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Atlassian MCP Server with CloudWatch Monitoring

Parameters:
  # Cloud Jira/Confluence parameters (optional)
  AtlassianBaseUrl:
    Type: String
    Description: "Base URL for Atlassian Cloud (e.g., https://yourcompany.atlassian.net)"
    Default: ""
  AtlassianUsername:
    Type: String
    Description: "Atlassian Cloud username/email"
    Default: ""
  AtlassianApiToken:
    Type: String
    NoEcho: true
    Description: "Atlassian Cloud API token"
    Default: ""
  
  # Cloud Bitbucket parameters (optional)
  BitbucketWorkspace:
    Type: String
    Description: "Bitbucket Cloud workspace name"
    Default: ""
  BitbucketApiToken:
    Type: String
    NoEcho: true
    Description: "Bitbucket Cloud API token"
    Default: ""
  
  # Data Center Jira parameters (optional)
  JiraBaseUrl:
    Type: String
    Description: "Jira Data Center base URL"
    Default: ""
  JiraPatToken:
    Type: String
    NoEcho: true
    Description: "Jira Data Center Personal Access Token"
    Default: ""
  
  # Data Center Confluence parameters (optional)
  ConfluenceBaseUrl:
    Type: String
    Description: "Confluence Data Center base URL"
    Default: ""
  ConfluencePatToken:
    Type: String
    NoEcho: true
    Description: "Confluence Data Center Personal Access Token"
    Default: ""
  
  # Data Center Bitbucket parameters (optional)
  BitbucketBaseUrl:
    Type: String
    Description: "Bitbucket Data Center base URL"
    Default: ""
  BitbucketPatToken:
    Type: String
    NoEcho: true
    Description: "Bitbucket Data Center Personal Access Token"
    Default: ""
  BitbucketProject:
    Type: String
    Description: "Bitbucket Data Center project key"
    Default: ""
  
  # Monitoring
  AlertEmail:
    Type: String
    Description: "Email address for CloudWatch alerts (optional)"
    Default: ""

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.11
  Api:
    Auth:
      ApiKeyRequired: true

Resources:
  AtlassianMCPFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_handler.lambda_handler
      Runtime: python3.11
      Environment:
        Variables:
          ATLASSIAN_BASE_URL: !Ref AtlassianBaseUrl
          ATLASSIAN_USERNAME: !Ref AtlassianUsername
          ATLASSIAN_API_TOKEN: !Ref AtlassianApiToken
          JIRA_BASE_URL: !Ref JiraBaseUrl
          JIRA_PAT_TOKEN: !Ref JiraPatToken
          CONFLUENCE_BASE_URL: !Ref ConfluenceBaseUrl
          CONFLUENCE_PAT_TOKEN: !Ref ConfluencePatToken
          BITBUCKET_BASE_URL: !Ref BitbucketBaseUrl
          BITBUCKET_WORKSPACE: !Ref BitbucketWorkspace
          BITBUCKET_API_TOKEN: !Ref BitbucketApiToken
          BITBUCKET_PROJECT: !Ref BitbucketProject
          BITBUCKET_PAT_TOKEN: !Ref BitbucketPatToken
      Policies:
        - CloudWatchPutMetricPolicy: {}
      Events:
        MCPApi:
          Type: Api
          Properties:
            Path: /mcp
            Method: post
        MCPApiGet:
          Type: Api
          Properties:
            Path: /mcp
            Method: get

  MCPLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AtlassianMCPFunction}'
      RetentionInDays: 14

  MCPApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn:
      - ServerlessRestApiProdStage
    Properties:
      Name: AtlassianMCPApiKey
      Enabled: true

  MCPUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - ServerlessRestApiProdStage
    Properties:
      UsagePlanName: AtlassianMCPUsagePlan
      ApiStages:
        - ApiId: !Ref ServerlessRestApi
          Stage: Prod
      Throttle:
        RateLimit: 100
        BurstLimit: 200

  MCPUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref MCPApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref MCPUsagePlan

  # SNS Topic for Alerts
  AlertTopic:
    Type: AWS::SNS::Topic
    Condition: HasAlertEmail
    Properties:
      TopicName: AtlassianMCPAlerts
      Subscription:
        - Endpoint: !Ref AlertEmail
          Protocol: email

  # CloudWatch Alarms
  ErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: HasAlertEmail
    Properties:
      AlarmName: AtlassianMCP-Errors
      AlarmDescription: Alert when Lambda function has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref AtlassianMCPFunction
      AlarmActions:
        - !Ref AlertTopic

  ThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: HasAlertEmail
    Properties:
      AlarmName: AtlassianMCP-Throttles
      AlarmDescription: Alert when Lambda function is throttled
      MetricName: Throttles
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref AtlassianMCPFunction
      AlarmActions:
        - !Ref AlertTopic

  DurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: HasAlertEmail
    Properties:
      AlarmName: AtlassianMCP-SlowResponse
      AlarmDescription: Alert when Lambda function is slow
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 25000
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref AtlassianMCPFunction
      AlarmActions:
        - !Ref AlertTopic

  ApiGateway4xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: HasAlertEmail
    Properties:
      AlarmName: AtlassianMCP-ClientErrors
      AlarmDescription: Alert on high rate of 4xx errors
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 20
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Ref AWS::StackName
        - Name: Stage
          Value: Prod
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  ApiGateway5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: HasAlertEmail
    Properties:
      AlarmName: AtlassianMCP-ServerErrors
      AlarmDescription: Alert on any 5xx errors
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Ref AWS::StackName
        - Name: Stage
          Value: Prod
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

Conditions:
  HasAlertEmail: !Not [!Equals [!Ref AlertEmail, ""]]

Outputs:
  MCPApiUrl:
    Description: API Gateway endpoint URL for MCP server
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/mcp'
  
  MCPFunctionArn:
    Description: MCP Lambda Function ARN
    Value: !GetAtt AtlassianMCPFunction.Arn
  
  MCPApiKeyId:
    Description: API Key ID (use 'aws apigateway get-api-key --api-key <id> --include-value' to get the key)
    Value: !Ref MCPApiKey
  
  AlertTopicArn:
    Description: SNS Topic ARN for alerts (if email provided)
    Condition: HasAlertEmail
    Value: !Ref AlertTopic