JIRA_TOOLS = [
    {"name": "search_jira", "description": "Search Jira issues using JQL"},
    {"name": "get_issue", "description": "Get Jira issue by key"},
    {"name": "create_issue", "description": "Create new Jira issue"},
    {"name": "update_issue", "description": "Update Jira issue"},
    {"name": "add_comment", "description": "Add comment to Jira issue"},
    {"name": "get_issue_comments", "description": "Get comments on Jira issue"},
    {"name": "transition_issue", "description": "Change Jira issue status"},
    {"name": "get_issue_transitions", "description": "Get available transitions for issue"},
    {"name": "assign_issue", "description": "Assign Jira issue to user"},
    {"name": "delete_issue", "description": "Delete Jira issue"},
    {"name": "list_projects", "description": "List all Jira projects"},
    {"name": "get_project", "description": "Get Jira project details"},
    {"name": "get_issue_attachments", "description": "Get attachments for Jira issue"},
    {"name": "get_issue_watchers", "description": "Get watchers for Jira issue"},
    {"name": "get_user", "description": "Get Jira user details by account ID"},
    {"name": "search_users", "description": "Search Jira users by name or email"},
    {"name": "get_current_user", "description": "Get authenticated Jira user information"},
    {"name": "link_issues", "description": "Create a link between two Jira issues"},
    {"name": "add_worklog", "description": "Log time spent on a Jira issue"},
    {"name": "get_worklogs", "description": "Get time tracking data for a Jira issue"},
    {"name": "add_label", "description": "Add a label to a Jira issue"},
    {"name": "search_by_assignee", "description": "Find Jira issues by assignee"},
    {"name": "search_by_reporter", "description": "Find Jira issues by reporter"},
    {"name": "get_recent_issues", "description": "Get recently updated Jira issues"},
    {"name": "set_priority", "description": "Change Jira issue priority"},
    {"name": "list_boards", "description": "Get all Scrum/Kanban boards"},
    {"name": "get_board_issues", "description": "Get issues on a board"},
    {"name": "list_sprints", "description": "Get sprints for a board"},
    {"name": "get_sprint_issues", "description": "Get issues in a sprint"},
    {"name": "get_user_permissions", "description": "Check user permissions"},
    {"name": "add_attachment", "description": "Upload file to Jira issue"}
]

CONFLUENCE_TOOLS = [
    {"name": "search_confluence", "description": "Search Confluence pages"},
    {"name": "get_page", "description": "Get Confluence page by ID. Large pages are chunked - check has_more in body.storage and call again with offset=<previous offset + chunk_size> to read subsequent chunks."},
    {"name": "get_page_by_title", "description": "Get Confluence page by title. Large pages are chunked - check has_more in body.storage and call again with offset=<previous offset + chunk_size> to read subsequent chunks."},
    {"name": "create_page", "description": "Create new Confluence page"},
    {"name": "update_page", "description": "Update Confluence page"},
    {"name": "delete_page", "description": "Delete Confluence page"},
    {"name": "list_pages", "description": "List pages in Confluence space"},
    {"name": "get_space", "description": "Get Confluence space details"},
    {"name": "list_spaces", "description": "List all Confluence spaces"},
    {"name": "get_page_comments", "description": "Get comments on Confluence page"},
    {"name": "add_page_comment", "description": "Add comment to Confluence page"},
    {"name": "get_page_attachments", "description": "Get attachments on Confluence page"},
    {"name": "get_confluence_user", "description": "Get Confluence user details by account ID"},
    {"name": "get_confluence_user_by_key", "description": "Get Confluence user details by userkey (from @mentions in page content)"},
    {"name": "search_confluence_users", "description": "Search Confluence users by name or email"},
    {"name": "add_page_label", "description": "Add a label to a Confluence page"},
    {"name": "get_page_labels", "description": "Get all labels on a Confluence page"},
    {"name": "get_page_history", "description": "Get Confluence page version history"},
    {"name": "get_page_restrictions", "description": "View Confluence page permissions"},
    {"name": "set_page_restrictions", "description": "Update Confluence page permissions"},
    {"name": "copy_page", "description": "Duplicate a Confluence page"},
    {"name": "get_user_content", "description": "Get Confluence pages created by a specific user (requires account_id)"},
    {"name": "get_recent_content", "description": "Get recently updated Confluence content (by any user)"},
    {"name": "restore_page_version", "description": "Restore previous version"},
    {"name": "search_by_author", "description": "Find content by author"},
    {"name": "search_by_label", "description": "Find content by label"},
    {"name": "move_page", "description": "Move a page to a different space or parent"},
    {"name": "get_child_pages", "description": "Get direct child pages of a page"},
    {"name": "get_descendants", "description": "Get all descendant pages of a page"},
    {"name": "get_ancestors", "description": "Get ancestor pages of a page"},
    {"name": "cql_search", "description": "Search Confluence using CQL (Confluence Query Language). Use 'creator = currentUser()' to find pages you created"}
]

BITBUCKET_TOOLS = [
    {"name": "search_bitbucket", "description": "Search Bitbucket repositories"},
    {"name": "search_files", "description": "Search for files in a repository by filename"},
    {"name": "get_repository", "description": "Get Bitbucket repository details"},
    {"name": "list_repositories", "description": "List all Bitbucket repositories"},
    {"name": "list_pull_requests", "description": "List pull requests in repository"},
    {"name": "get_pull_request", "description": "Get pull request details"},
    {"name": "create_pull_request", "description": "Create new pull request"},
    {"name": "get_file_content", "description": "Get file content from repository"},
    {"name": "list_commits", "description": "List commits in repository"},
    {"name": "get_commit", "description": "Get commit details"},
    {"name": "list_branches", "description": "List branches in repository"},
    {"name": "get_pull_request_diff", "description": "Get pull request diff"},
    {"name": "get_pull_request_comments", "description": "Get pull request comments"},
    {"name": "add_pr_comment", "description": "Add comment to pull request"},
    {"name": "approve_pull_request", "description": "Approve pull request"},
    {"name": "merge_pull_request", "description": "Merge pull request"},
    {"name": "get_commit_diff", "description": "Get commit diff"},
    {"name": "list_tags", "description": "List tags in repository"},
    {"name": "list_directory", "description": "List files in directory"},
    {"name": "update_pull_request", "description": "Update pull request"},
    {"name": "compare_commits", "description": "Compare two commits"},
    {"name": "add_pr_reviewer", "description": "Add a reviewer to a pull request"},
    {"name": "decline_pull_request", "description": "Decline a pull request"},
    {"name": "create_branch", "description": "Create a new branch"},
    {"name": "delete_branch", "description": "Delete a branch"},
    {"name": "get_bitbucket_user", "description": "Get Bitbucket user details"},
    {"name": "get_pr_activity", "description": "Get pull request activity/timeline"},
    {"name": "get_default_reviewers", "description": "Get default reviewers for repository"},
    {"name": "list_pull_requests_by_author", "description": "List pull requests by author"},
    {"name": "list_commits_by_author", "description": "List commits by author"},
    {"name": "request_changes", "description": "Request changes on pull request"},
    {"name": "get_branch_restrictions", "description": "Get branch permissions/restrictions"},
    {"name": "get_build_status", "description": "Get CI/CD build status for commit"},
    {"name": "create_webhook", "description": "Create repository webhook"}
]

TICKET_SUPPORT_TOOLS = [
    {"name": "get_open_support_tickets", "description": "Get list of open support tickets needing assignment, separated by type. Returns: alert_tickets (list of tickets with Alert in custom field), other_tickets (list of non-alert tickets), total counts."},
    {"name": "check_ticket_template", "description": "Check if Jira ticket follows defined template"},
    {"name": "suggest_assignee", "description": "Suggest who should be assigned to ticket based on team workload"},
    {"name": "get_team_workload", "description": "Get current workload for all team members"},
    {"name": "get_expertise_jql", "description": "Construct expertise JQL query for a member. Automatically extracts ticket fields and builds proper JQL. Returns: jql (ready to use with search_jira), extracted_values (shows what was extracted)."},
    {"name": "check_troubleshooting", "description": "Get troubleshooting documentation for alert ticket. Returns: ticket details (summary, description), Bitbucket URL extracted from description, list of Confluence troubleshooting docs. AI can then read code and supplement docs with code/SQL analysis."}
]
